server:
  port: 8066
rpc:
  name: rpc
  version: 2.0
  serverPort: 8080
  mock: false
  serializer: json
  registryConfig:
    registry: etcd
    address: http://localhost:2380
  retryStrategy: fixedInterval